"""Classify user intent before routing to maintenance agents or plant assistant."""

from __future__ import annotations

import re
from typing import Literal

Intent = Literal["greeting", "navigation", "general", "maintenance"]

GREETINGS = {"hi", "hello", "hey", "help", "thanks", "thank you", "ok", "okay", "good morning", "good evening"}

NAV_PATTERNS = [
    r"\bwhere\b.*\b(is|are|can i find|do i go)\b",
    r"\bhow\b.*\b(find|open|access|navigate|get to|reach)\b",
    r"\b(show|open|go to|take me to|navigate to)\b",
    r"\bwhich\b.*\b(page|section|tab|menu|screen)\b",
    r"\blive\s+monitor",
    r"\bmonitoring\s+(section|page|center)\b",
    r"\bcommand\s+center\b",
    r"\bnavigation\b",
    r"\bapp\s+sections?\b",
    r"\bwhat\s+pages?\b",
    r"\bmenu\b",
]

EQUIPMENT_CONTEXT_PATTERNS = [
    r"\bsummar",
    r"\bissues?\b",
    r"\bproblems?\b",
    r"\bstatus\b",
    r"\bcondition\b",
    r"\bhealth\b",
    r"\boverview\b",
    r"\bwhat'?s wrong\b",
    r"\bany\s+alerts?\b",
    r"\bopen\s+alerts?\b",
    r"\bcurrent\s+state\b",
    r"\btell\s+me\s+about\b",
    r"\bexplain\s+this\s+asset\b",
    r"\bwhat\s+happened\b",
    r"\brecent\s+fault",
    r"\balarm",
]

MAINTENANCE_PATTERNS = [
    r"\bvibrat",
    r"\btemperatur",
    r"\bfailure",
    r"\banomal",
    r"\bdiagnos",
    r"\bbearing",
    r"\bmotor\b",
    r"\bpump\b",
    r"\bcrane\b",
    r"\bconveyor\b",
    r"\bblower\b",
    r"\brul\b",
    r"\bhealth\s+score",
    r"\broot\s+cause",
    r"\bsafe\s+to\s+(run|keep|operate)",
    r"\bkeep\s+running\b",
    r"\bsafe\s+to\s+keep\b",
    r"\bspare\s+part",
    r"\bspare\s+parts",
    r"\bwhich\s+spare",
    r"\bwhat\s+spare",
    r"\bsop\b",
    r"\bmanual\b",
    r"\bmaintenance\s+action",
    r"\bwhat\s+is\s+causing",
    r"\bwhat\s+should\s+i\s+do",
    r"\bwhat\s+do\s+i\s+do",
    r"\bnext\s+step",
    r"\bwhy\s+is\b",
    r"\bequipment\s+issue",
    r"\bsensor\s+anomal",
    r"\bml\s+anomal",
    r"\bdegrad",
    r"\bcritical\s+risk",
    r"\bhigh\s+vibration",
    r"\boverheat",
    r"\bexplain\s+this\s+alert",
    r"\bdiagnose\s+this",
    r"\bshutdown\b",
    r"\bcontinue\s+operat",
]

FOLLOWUP_PATTERNS = [
    r"\bsafe\b",
    r"\bkeep\s+running\b",
    r"\bnext\b",
    r"\bshould\s+i\b",
    r"\bwhat\s+about\b",
    r"\bexplain\b",
    r"\bmore\s+detail",
    r"\bspare\b",
    r"\bpart\b",
    r"\bwhy\b",
    r"\bsop\b",
    r"\bmanual\b",
    r"\bprocedure\b",
    r"\brelevant\b",
    r"\bsection\b",
    r"\bwhich\s+spare",
    r"\bwhat\s+spare",
    r"\bneed\b",
    r"\border\b",
]

GENERAL_PATTERNS = [
    r"\bwhat\s+(is|are)\s+(this|the)\s+(app|platform|system|wizard)\b",
    r"\bwho\s+are\s+you\b",
    r"\b(ho|who)\s+are\s+you\b",
    r"\bwhat\s+is\s+your\s+name\b",
    r"\bintroduce\s+yourself\b",
    r"\bwhat\s+can\s+you\b",
    r"\bcapabilit",
    r"\bhelp\s+me\s+use\b",
    r"\bhow\s+does\s+this\s+(app|platform|work)\b",
    r"\bwhat\s+do\s+you\s+do\b",
]


def _normalize_for_greeting(text: str) -> str:
    """Strip punctuation so 'Hi!' and 'hello.' still count as greetings."""
    return re.sub(r"[^\w\s]", "", text.strip().lower()).strip()


def _is_greeting(message: str) -> bool:
    """Lightweight routing only — actual reply is generated by Agentic AI."""
    msg = _normalize_for_greeting(message)
    if not msg:
        return False
    if msg in GREETINGS:
        return True
    # Short casual openers: hi, hI, Hi!, hey, yo, sup, etc.
    if len(msg) <= 12 and msg.replace(" ", "").isalpha():
        starters = ("hi", "hey", "helo", "hii", "hiya", "yo", "sup", "howdy")
        if any(msg == s or msg.startswith(s + " ") for s in starters):
            return True
    words = msg.split()
    if words and words[0] in {"hi", "hello", "hey", "hiya", "howdy", "helo"} and len(words) <= 4:
        return True
    return False


def _matches(patterns: list[str], text: str) -> bool:
    return any(re.search(p, text) for p in patterns)


def _recent_maintenance_context(history: list[dict[str, str]] | None) -> bool:
    if not history:
        return False
    for msg in reversed(history[-6:]):
        content = (msg.get("content") or "").lower()
        if msg.get("role") == "assistant" and any(
            k in content
            for k in (
                "risk:",
                "rul",
                "failure probability",
                "probable cause",
                "maintenance assessment",
                "## summary",
                "key findings",
                "maintenance decision",
                "recommended action",
            )
        ):
            return True
        if msg.get("role") == "user" and _matches(MAINTENANCE_PATTERNS, content):
            return True
    return False


def classify_intent(
    message: str,
    *,
    chat_mode: str = "assistant",
    equipment_code: str | None = None,
    conversation_history: list[dict[str, str]] | None = None,
) -> Intent:
    msg = message.strip().lower()
    if not msg:
        return "general"
    if _is_greeting(message):
        return "greeting"

    is_nav = _matches(NAV_PATTERNS, msg)
    is_maint = _matches(MAINTENANCE_PATTERNS, msg)
    is_general = _matches(GENERAL_PATTERNS, msg)

    if chat_mode == "diagnosis":
        if is_nav and not is_maint:
            return "navigation"
        return "maintenance"

    is_equipment_ctx = bool(equipment_code) and _matches(EQUIPMENT_CONTEXT_PATTERNS, msg)
    in_maint_thread = _recent_maintenance_context(conversation_history)

    if in_maint_thread and (_matches(FOLLOWUP_PATTERNS, msg) or is_maint or is_equipment_ctx):
        return "maintenance"

    if is_nav and not is_maint and not is_equipment_ctx:
        return "navigation"
    if is_maint or is_equipment_ctx:
        return "maintenance"
    if is_general:
        return "general"
    if is_nav:
        return "navigation"

    if equipment_code and chat_mode == "diagnosis":
        return "maintenance"

    if _recent_maintenance_context(conversation_history):
        return "maintenance"

    return "general"
